# -*- coding: utf-8 -*-
"""Replace Reto 5 prompt body + RETO_CASES.r5 fields with the official editable Excel prompt."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INDEX = ROOT / "index.html"

FN = r'''  /** Prompt Reto 5: modo edición de plantilla Excel (.xlsx real). */
  function buildPromptR5Text(f) {
    const bracket = (v) => "[[" + (v || "") + "]]";
    return [
      "PROMPT CONFIGURABLE PARA COPILOT",
      "MODO EDICIÓN DE PLANTILLA EXCEL (.XLSX REAL)",
      "CASO 5 · COMPARACIÓN DOCUMENTAL",
      "",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "INSTRUCCIONES PARA EL PARTICIPANTE",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "Revisa los campos de configuración y ajústalos únicamente si cambia el caso.",
      "",
      "Proporciona a Copilot estos tres archivos:",
      "",
      "1. MCP365_P05_Comparacion_documental.xlsx",
      "2. PRO-OPS-12_Version_3_1.pdf",
      "3. PRO-OPS-12_Version_4_0.pdf",
      "",
      "También pueden utilizarse como fuentes las versiones Word equivalentes, siempre que correspondan exactamente a las versiones 3.1 y 4.0.",
      "",
      "No conviertas previamente el Excel en Word, PDF, CSV, tabla de texto ni imagen.",
      "",
      "El resultado esperado es una copia diligenciada del archivo Excel original.",
      "",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "1. CONFIGURACIÓN DEL ANÁLISIS",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "ROL DE COPILOT",
      "",
      bracket(f.rol),
      "",
      "APLICACIÓN DE ORIGEN",
      "",
      bracket(f.app),
      "",
      "DOCUMENTO ANTERIOR",
      "",
      bracket(f.doc_anterior),
      "",
      "DOCUMENTO VIGENTE",
      "",
      bracket(f.doc_vigente),
      "",
      "ARCHIVO EXCEL QUE SE DEBE COMPLETAR",
      "",
      bracket(f.archivo),
      "",
      "OBJETIVO DEL ANÁLISIS",
      "",
      bracket(f.objetivo),
      "",
      "HOJA PRINCIPAL QUE SE PUEDE EDITAR",
      "",
      bracket(f.hoja_autorizada),
      "",
      "SECCIONES AUTORIZADAS",
      "",
      bracket("\n" + (f.secciones || "") + "\n"),
      "",
      "FILAS DE LA MATRIZ QUE SE DEBEN ANALIZAR",
      "",
      bracket("\n" + (f.filas_matriz || "") + "\n"),
      "",
      "COLUMNAS EDITABLES DE LA MATRIZ",
      "",
      bracket("\n" + (f.columnas_editables || "") + "\n"),
      "",
      "COLUMNA QUE DEBE CONSERVARSE SIN CAMBIOS",
      "",
      bracket(f.columna_sin_cambios),
      "",
      "TIPO DE EVIDENCIA",
      "",
      bracket(f.tipo_evidencia),
      "",
      "FORMATO DE EVIDENCIA",
      "",
      bracket("\n" + (f.formato_evidencia || "") + "\n"),
      "",
      "RESPUESTA CUANDO NO EXISTA INFORMACIÓN",
      "",
      bracket(f.vacio),
      "",
      "NIVEL DE DETALLE",
      "",
      bracket(f.detalle),
      "",
      "NOMBRE DEL ARCHIVO DE SALIDA",
      "",
      bracket(f.salida),
      "",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "2. INSTRUCCIÓN PARA COPILOT",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "ACTÚA EN MODO EDICIÓN DE PLANTILLA EXCEL (.XLSX REAL).",
      "",
      "Asume el rol definido en la configuración.",
      "",
      "Analiza exclusivamente las versiones 3.1 y 4.0 de PRO-OPS-12 y completa el archivo Excel especificado.",
      "",
      "IMPORTANTE",
      "",
      "El archivo MCP365_P05_Comparacion_documental.xlsx es la plantilla oficial.",
      "",
      "Debes trabajar directamente sobre una copia editable del libro original.",
      "",
      "No debes crear, reconstruir, resumir ni rediseñar el libro a partir de una representación textual.",
      "",
      "No generes una tabla nueva en Word.",
      "",
      "No entregues el resultado como tabla en el chat.",
      "",
      "No conviertas el archivo a CSV.",
      "",
      "No conviertas las hojas en documentos independientes.",
      "",
      "No reemplaces el libro por un archivo Excel simplificado.",
      "",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "3. PRECONDICIÓN DE LOS ARCHIVOS",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "Antes de comenzar:",
      "",
      "1. Comprueba que tienes acceso de lectura a:",
      "",
      "* PRO-OPS-12_Version_3_1.pdf",
      "* PRO-OPS-12_Version_4_0.pdf",
      "",
      "2. Comprueba que tienes acceso editable al archivo:",
      "",
      "MCP365_P05_Comparacion_documental.xlsx",
      "",
      "3. Confirma que el libro contiene estas cuatro hojas:",
      "",
      "* Instrucciones.",
      "* Comparación.",
      "* Validación y calidad.",
      "* Catálogos.",
      "",
      "4. Si solamente puedes ver una imagen, vista previa, descripción o representación textual del Excel, detente.",
      "",
      "5. Si no tienes acceso al archivo `.xlsx` real, responde:",
      "",
      "“No tengo acceso editable al archivo Excel original. Adjunta o habilita MCP365_P05_Comparacion_documental.xlsx para completar la plantilla sin reconstruirla.”",
      "",
      "6. Mientras no tengas acceso al `.xlsx`, no produzcas una versión alternativa.",
      "",
      "7. Si falta uno de los dos procedimientos, indica exactamente cuál falta y no inicies una comparación parcial.",
      "",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "4. TAREA",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "1. Crea una copia editable de:",
      "",
      "MCP365_P05_Comparacion_documental.xlsx",
      "",
      "2. Analiza completamente:",
      "",
      "* PRO-OPS-12 versión 3.1.",
      "* PRO-OPS-12 versión 4.0.",
      "",
      "3. Trabaja únicamente en la hoja:",
      "",
      "Comparación.",
      "",
      "4. Completa las doce filas existentes de la sección:",
      "",
      "“4. Matriz de cambios · LLENAR CON COPILOT”.",
      "",
      "5. Completa los hallazgos aplicables de la sección:",
      "",
      "“5. Elementos nuevos, eliminados y contradicciones · LLENAR CON COPILOT”.",
      "",
      "6. Completa los seis campos de la sección:",
      "",
      "“6. Recomendación de transición · LLENAR CON COPILOT”.",
      "",
      "7. Utiliza las listas desplegables existentes cuando la celda las incluya.",
      "",
      "8. Conserva las fórmulas del resumen automático.",
      "",
      "9. Conserva el estado de validación de las doce filas como:",
      "",
      "“Pendiente”.",
      "",
      "10. Guarda la copia con el nombre exacto:",
      "",
      "MCP365_P05_Comparacion_documental_completada.xlsx",
      "",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "5. REGLAS PARA LA MATRIZ DE CAMBIOS",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "La matriz contiene doce filas temáticas.",
      "",
      "No agregues, elimines, reordenes ni renombres esas filas.",
      "",
      "No modifiques las columnas “#” y “Tema / sección”.",
      "",
      "Completa las siguientes columnas:",
      "",
      "VERSIÓN 3.1",
      "",
      "Resume la regla, condición, plazo, obligación o responsabilidad establecida en la versión 3.1.",
      "",
      "No copies párrafos completos.",
      "",
      "EVIDENCIA V3.1",
      "",
      "Incluye una referencia verificable con este formato:",
      "",
      "V3.1 · Sección [número o título] · “[fragmento breve]”",
      "",
      "VERSIÓN 4.0",
      "",
      "Resume la regla, condición, plazo, obligación o responsabilidad establecida en la versión 4.0.",
      "",
      "Diferencia claramente una obligación nueva de una simple reescritura.",
      "",
      "EVIDENCIA V4.0",
      "",
      "Incluye una referencia verificable con este formato:",
      "",
      "V4.0 · Sección [número o título] · “[fragmento breve]”",
      "",
      "TIPO DE CAMBIO",
      "",
      "Selecciona únicamente uno de los valores disponibles:",
      "",
      "* Textual.",
      "* Significado.",
      "* Ambos.",
      "",
      "Utiliza “Textual” cuando cambie la redacción, pero la obligación operativa se mantenga.",
      "",
      "Utiliza “Significado” cuando cambien plazos, responsables, autorizaciones, evidencias, condiciones, niveles de riesgo o consecuencias.",
      "",
      "Utiliza “Ambos” cuando exista una reescritura y también un cambio operativo material.",
      "",
      "NATURALEZA",
      "",
      "Selecciona únicamente uno:",
      "",
      "* Modificado.",
      "* Nuevo.",
      "* Eliminado.",
      "* Sin cambio.",
      "",
      "Utiliza “Nuevo” cuando la versión 4.0 incorpore una obligación sin equivalente verificable en la versión 3.1.",
      "",
      "Utiliza “Eliminado” cuando una obligación de la versión 3.1 ya no aparezca ni tenga equivalente en la versión 4.0.",
      "",
      "No declares una eliminación solamente porque cambió la ubicación de la regla.",
      "",
      "IMPACTO POSIBLE",
      "",
      "Explica brevemente qué podría ocurrir si el cambio no se implementa correctamente.",
      "",
      "Presenta el impacto como posibilidad, no como hecho confirmado.",
      "",
      "Ejemplos de estructura:",
      "",
      "* “Podría generar…”",
      "* “Puede requerir…”",
      "* “Existe riesgo de…”",
      "* “Obliga a ajustar…”",
      "",
      "No inventes impactos financieros, legales, técnicos o comunitarios que no puedan derivarse razonablemente de los documentos.",
      "",
      "ACCIÓN DE TRANSICIÓN",
      "",
      "Formula una acción concreta iniciando con un verbo.",
      "",
      "Ejemplos:",
      "",
      "* Actualizar…",
      "* Comunicar…",
      "* Configurar…",
      "* Retirar…",
      "* Capacitar…",
      "* Verificar…",
      "* Migrar…",
      "* Aprobar…",
      "",
      "La acción debe responder al cambio identificado.",
      "",
      "APROBADOR SUGERIDO",
      "",
      "Utiliza únicamente personas, cargos o áreas que aparezcan en los procedimientos.",
      "",
      "No inventes comités ni cargos.",
      "",
      "Si no puede determinarse un aprobador, escribe:",
      "",
      "“No especificado”.",
      "",
      "PRIORIDAD",
      "",
      "Selecciona:",
      "",
      "* Alta.",
      "* Media.",
      "* Baja.",
      "",
      "Utiliza “Alta” cuando el cambio afecte seguridad, continuidad, autorización de inicio, vigencia, cierre, contradicciones o cumplimiento obligatorio.",
      "",
      "Utiliza “Media” cuando afecte responsabilidades, evidencias, comunicaciones, registros o procesos internos.",
      "",
      "Utiliza “Baja” cuando corresponda principalmente a ajustes administrativos o de redacción sin efecto operativo material.",
      "",
      "ESTADO DE VALIDACIÓN",
      "",
      "No modifiques esta columna.",
      "",
      "Las doce filas deben permanecer como:",
      "",
      "“Pendiente”.",
      "",
      "Copilot no puede marcar una fila como “Validado”, porque esa decisión corresponde a la validación humana.",
      "",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "6. REGLAS PARA ELEMENTOS NUEVOS, ELIMINADOS Y CONTRADICCIONES",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "Localiza la sección:",
      "",
      "“5. Elementos nuevos, eliminados y contradicciones · LLENAR CON COPILOT”.",
      "",
      "Completa una fila por cada hallazgo relevante.",
      "",
      "Utiliza únicamente estos tipos:",
      "",
      "* Elemento nuevo.",
      "* Elemento eliminado.",
      "* Contradicción detectada.",
      "",
      "DESCRIPCIÓN",
      "",
      "Explica claramente el hallazgo y las reglas involucradas.",
      "",
      "EVIDENCIA PRECISA",
      "",
      "Cita versión, sección o anexo y fragmento breve.",
      "",
      "Cuando exista una contradicción, incluye obligatoriamente las dos referencias que entran en conflicto.",
      "",
      "Formato recomendado:",
      "",
      "V4.0 · Sección [número] · “[fragmento]”",
      "vs.",
      "V4.0 · Anexo [letra] · “[fragmento]”",
      "",
      "No resuelvas una contradicción mediante suposición.",
      "",
      "RIESGO SI SE IGNORA",
      "",
      "Explica el posible efecto operativo de utilizar simultáneamente reglas incompatibles o de no implementar un elemento nuevo.",
      "",
      "ACCIÓN RECOMENDADA",
      "",
      "Formula una acción de verificación, aclaración, aprobación o corrección.",
      "",
      "Ejemplos:",
      "",
      "* Solicitar aclaración al área emisora.",
      "* Definir cuál regla prevalece.",
      "* Corregir el anexo.",
      "* Actualizar el procedimiento.",
      "* Comunicar la decisión formal.",
      "* Suspender la aplicación de la regla contradictoria hasta su aclaración.",
      "",
      "Si existen menos hallazgos que filas disponibles, deja las filas restantes completamente vacías.",
      "",
      "No dejes filas parcialmente diligenciadas.",
      "",
      "No inventes hallazgos para llenar todas las filas.",
      "",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "7. REGLAS PARA LA RECOMENDACIÓN DE TRANSICIÓN",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "Localiza la sección:",
      "",
      "“6. Recomendación de transición · LLENAR CON COPILOT”.",
      "",
      "Completa exclusivamente el espacio ubicado a la derecha de cada etiqueta.",
      "",
      "No modifiques las etiquetas.",
      "",
      "REGLA EFECTIVA",
      "",
      "Indica qué versión debe aplicarse y desde qué fecha.",
      "",
      "EXCEPCIONES",
      "",
      "Incluye solamente excepciones expresamente establecidas en los procedimientos.",
      "",
      "No inventes periodos de gracia.",
      "",
      "ACCIONES OBLIGATORIAS",
      "",
      "Resume las acciones que deben ejecutarse para pasar de la versión anterior a la nueva.",
      "",
      "RESPONSABLE PRINCIPAL",
      "",
      "Indica el cargo o área con mayor responsabilidad explícita sobre la transición.",
      "",
      "Si no está definido, escribe:",
      "",
      "“No especificado”.",
      "",
      "FECHA LÍMITE",
      "",
      "Incluye únicamente una fecha expresamente establecida.",
      "",
      "No calcules una fecha por inferencia.",
      "",
      "EVIDENCIA DE CIERRE",
      "",
      "Indica el registro, documento o constancia que permitiría verificar la terminación de la transición.",
      "",
      "La recomendación debe distinguir entre:",
      "",
      "* Regla vigente.",
      "* Excepción temporal.",
      "* Acción obligatoria.",
      "* Responsable.",
      "* Fecha.",
      "* Evidencia.",
      "",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "8. REGLAS PARA INFORMACIÓN AUSENTE",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "Cuando una versión no contenga información sobre uno de los doce temas, escribe:",
      "",
      "“No especificado”.",
      "",
      "Cuando la versión 4.0 incorpore una regla nueva sin equivalente identificable en la versión 3.1, escribe en la columna de la versión 3.1:",
      "",
      "“No identificado en esta versión”.",
      "",
      "Cuando una regla de la versión 3.1 haya sido eliminada, escribe en la columna de la versión 4.0:",
      "",
      "“No identificado en esta versión”.",
      "",
      "No presentes la ausencia como definitiva si no revisaste completamente el documento.",
      "",
      "No inventes equivalencias entre secciones que tienen objetivos diferentes.",
      "",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "9. HOJAS Y SECCIONES RESTRINGIDAS",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "No modifiques la hoja:",
      "",
      "“Instrucciones”.",
      "",
      "No modifiques la hoja:",
      "",
      "“Validación y calidad”.",
      "",
      "No modifiques la hoja:",
      "",
      "“Catálogos”.",
      "",
      "En la hoja “Comparación”, no modifiques:",
      "",
      "* El título principal.",
      "* El subtítulo.",
      "* La sección 1: Datos del participante.",
      "* La sección 2: Identificación de documentos.",
      "* La sección 3: Resumen automático de avance.",
      "* Los indicadores automáticos.",
      "* Las fórmulas.",
      "* Las columnas “#” y “Tema / sección”.",
      "* Los nombres de los doce temas.",
      "* Los títulos de sección.",
      "* Los encabezados.",
      "* La columna “Estado de validación”.",
      "* Las celdas que contienen “Pendiente”.",
      "* Las etiquetas de la recomendación de transición.",
      "",
      "La validación humana y el control de calidad deben permanecer completamente vacíos.",
      "",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "10. CONSERVACIÓN DE LA PLANTILLA EXCEL",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "Mantén sin modificaciones:",
      "",
      "* Las cuatro hojas originales.",
      "* Los nombres y el orden de las hojas.",
      "* Las fórmulas.",
      "* Las listas desplegables.",
      "* Las validaciones de datos.",
      "* Las celdas combinadas.",
      "* Los colores.",
      "* Los bordes.",
      "* Los anchos de columna.",
      "* La altura configurada de las filas.",
      "* Los títulos.",
      "* Los subtítulos.",
      "* La numeración.",
      "* Los temas prellenados.",
      "* Los indicadores.",
      "* Los campos administrativos.",
      "* La inmovilización de paneles.",
      "* El formato institucional.",
      "* Las celdas protegidas.",
      "* Las secciones de validación humana.",
      "* Las secciones de control de calidad.",
      "",
      "Puedes aumentar la altura de una fila solamente cuando sea indispensable para visualizar el contenido.",
      "",
      "No cambies el ancho de las columnas.",
      "",
      "No descombines celdas.",
      "",
      "No insertes filas ni columnas.",
      "",
      "No crees hojas nuevas.",
      "",
      "No ocultes hojas.",
      "",
      "No elimines fórmulas o listas desplegables.",
      "",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "11. PROHIBICIONES",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "• No crees un libro Excel desde cero.",
      "",
      "• No reemplaces la plantilla por una hoja nueva.",
      "",
      "• No entregues únicamente la matriz diligenciada.",
      "",
      "• No conviertas el Excel en Word, PDF, CSV, HTML o tabla Markdown.",
      "",
      "• No escribas el resultado únicamente en el panel de Copilot.",
      "",
      "• No modifiques las hojas restringidas.",
      "",
      "• No diligencies validación humana.",
      "",
      "• No diligencies control de calidad.",
      "",
      "• No marques ninguna fila como “Validado”.",
      "",
      "• No inventes fechas, obligaciones, responsables, aprobadores, impactos o excepciones.",
      "",
      "• No presentes una inferencia como hecho.",
      "",
      "• No elimines filas vacías.",
      "",
      "• No reemplaces fórmulas por valores fijos.",
      "",
      "• No alteres los indicadores automáticos.",
      "",
      "• No agregues introducciones, conclusiones o explicaciones fuera de las secciones autorizadas.",
      "",
      "• No copies bloques extensos de los procedimientos.",
      "",
      "• No ignores los anexos.",
      "",
      "• No asumas que el cuerpo del procedimiento siempre coincide con sus anexos.",
      "",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "12. VERIFICACIÓN OBLIGATORIA",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "Antes de guardar, verifica:",
      "",
      "ARCHIVO",
      "",
      "1. El resultado es un archivo `.xlsx` real.",
      "2. El libro conserva las cuatro hojas originales.",
      "3. No se crearon hojas adicionales.",
      "4. El archivo abre correctamente.",
      "5. El nombre final es exacto.",
      "",
      "MATRIZ",
      "",
      "6. Las doce filas temáticas están diligenciadas.",
      "7. Cada fila compara las versiones 3.1 y 4.0.",
      "8. Cada fila contiene evidencia de ambas versiones cuando exista.",
      "9. El tipo de cambio utiliza un valor permitido.",
      "10. La naturaleza utiliza un valor permitido.",
      "11. La prioridad utiliza un valor permitido.",
      "12. La columna Estado de validación continúa como “Pendiente”.",
      "13. No existen filas parcialmente diligenciadas.",
      "14. No se inventaron responsables ni aprobadores.",
      "",
      "HALLAZGOS",
      "",
      "15. Los elementos nuevos están sustentados.",
      "16. Los elementos eliminados están sustentados.",
      "17. Las contradicciones incluyen las dos evidencias en conflicto.",
      "18. Las filas no utilizadas permanecen completamente vacías.",
      "",
      "TRANSICIÓN",
      "",
      "19. Se identificó la versión vigente.",
      "20. Las excepciones provienen de la fuente.",
      "21. Las acciones comienzan con un verbo.",
      "22. El responsable y la fecha no fueron inferidos.",
      "23. La evidencia de cierre es verificable.",
      "",
      "FORMATO",
      "",
      "24. Las fórmulas permanecen activas.",
      "25. Los indicadores automáticos funcionan.",
      "26. Las listas desplegables siguen disponibles.",
      "27. Los colores, bordes y celdas combinadas se conservaron.",
      "28. No se modificaron las hojas Instrucciones, Validación y calidad o Catálogos.",
      "29. La validación humana permanece vacía.",
      "30. El control de calidad permanece vacío.",
      "",
      "Si alguna comprobación falla, corrige únicamente las celdas autorizadas antes de entregar.",
      "",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "13. ENTREGA",
      "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━",
      "",
      "Guarda la copia completada con el nombre exacto:",
      "",
      "MCP365_P05_Comparacion_documental_completada.xlsx",
      "",
      "Entrega el libro completo con sus cuatro hojas originales.",
      "",
      "No entregues únicamente una hoja.",
      "",
      "No entregues un resumen adicional.",
      "",
      "No entregues tablas en el chat.",
      "",
      "No conviertas el resultado a otro formato.",
      "",
      "Si no puedes conservar la plantilla, sus fórmulas, listas desplegables, hojas y formato, informa la limitación y no reconstruyas el archivo.",
      "",
      "Mensaje final esperado:",
      "",
      "“Comparación aplicada en la plantilla Excel original. Se completaron la matriz de cambios, los hallazgos documentales y la recomendación de transición. La validación humana y el control de calidad permanecen vacíos.”"
    ].join("\n");
  }
'''

R5_FIELDS = r'''    "fields": [
      ["rol", "Rol de Copilot", "Analista de procesos y control documental especializado en comparar versiones de procedimientos, identificar cambios normativos, evaluar impactos operativos y formular acciones de transición."],
      ["app", "Aplicación de origen", "Copilot en Outlook."],
      ["doc_anterior", "Documento anterior", "PRO-OPS-12_Version_3_1.pdf · Versión histórica vigente hasta el 28/02/2026."],
      ["doc_vigente", "Documento vigente", "PRO-OPS-12_Version_4_0.pdf · Versión vigente desde el 01/03/2026."],
      ["archivo", "Archivo Excel que se debe completar", "MCP365_P05_Comparacion_documental.xlsx."],
      ["objetivo", "Objetivo del análisis", "Comparar integralmente las versiones 3.1 y 4.0 de PRO-OPS-12 para identificar cambios textuales y de significado, obligaciones nuevas o eliminadas, impactos posibles, contradicciones documentales, responsables, necesidades de aprobación y acciones de transición."],
      ["hoja_autorizada", "Hoja principal que se puede editar", "Comparación."],
      ["secciones", "Secciones autorizadas", "4. Matriz de cambios · LLENAR CON COPILOT.\n5. Elementos nuevos, eliminados y contradicciones · LLENAR CON COPILOT.\n6. Recomendación de transición · LLENAR CON COPILOT."],
      ["filas_matriz", "Filas de la matriz que se deben analizar", "1. Anticipación a usuarios.\n2. Autorización de inicio.\n3. Registro de hallazgos.\n4. Horario y cierre.\n5. Clasificación de impacto.\n6. Confirmación de recursos.\n7. Criterios de detención.\n8. Evidencia y trazabilidad.\n9. Conservación de registros.\n10. Responsabilidad del contratista.\n11. Indicadores.\n12. Régimen de transición."],
      ["columnas_editables", "Columnas editables de la matriz", "• Versión 3.1.\n• Evidencia V3.1.\n• Versión 4.0.\n• Evidencia V4.0.\n• Tipo de cambio.\n• Naturaleza.\n• Impacto posible.\n• Acción de transición.\n• Aprobador sugerido.\n• Prioridad."],
      ["columna_sin_cambios", "Columna que debe conservarse sin cambios", "Estado de validación · Debe permanecer como “Pendiente”."],
      ["tipo_evidencia", "Tipo de evidencia", "Versión + sección o anexo + fragmento textual breve y verificable."],
      ["formato_evidencia", "Formato de evidencia", "V3.1 · Sección [número o título] · “[fragmento breve]”\n\nV4.0 · Sección [número o título] · “[fragmento breve]”"],
      ["vacio", "Respuesta cuando no exista información", "No especificado."],
      ["detalle", "Nivel de detalle", "Operativo y verificable. Máximo tres oraciones por celda. Evita copiar párrafos extensos."],
      ["salida", "Nombre del archivo de salida", "MCP365_P05_Comparacion_documental_completada.xlsx."]
    ],'''


def replace_fn(text: str) -> str:
    start = text.find("  /** Prompt Reto 5: modo edición de plantilla Excel")
    if start < 0:
        raise SystemExit("buildPromptR5Text header not found")
    end = text.find("\n\n  /* ========== RETO ENGINE", start)
    if end < 0:
        raise SystemExit("RETO ENGINE marker after R5 not found")
    return text[:start] + FN.rstrip() + text[end:]


def replace_fields(text: str) -> str:
    # Replace only the fields array inside r5
    r5 = text.find('  "r5": {')
    if r5 < 0:
        raise SystemExit("r5 not found")
    r6 = text.find('  "r6": {', r5)
    block = text[r5:r6]
    f_start = block.find('    "fields": [')
    if f_start < 0:
        raise SystemExit("r5 fields not found")
    f_end = block.find('    "checklist": [', f_start)
    if f_end < 0:
        raise SystemExit("r5 checklist not found")
    new_block = block[:f_start] + R5_FIELDS + "\n" + block[f_end:]
    return text[:r5] + new_block + text[r6:]


def main():
    text = INDEX.read_text(encoding="utf-8")
    text = replace_fn(text)
    print("Replaced buildPromptR5Text")
    text = replace_fields(text)
    print("Replaced RETO_CASES.r5 fields")
    INDEX.write_text(text, encoding="utf-8")
    print(f"OK -> {INDEX}")


if __name__ == "__main__":
    main()
